[env:audiokit]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    pschatzmann/arduino-audiokit
    tzapu/WiFiManager
    bblanchon/ArduinoJson
build_flags =
    -DCORE_DEBUG_LEVEL=3
