[env:audiokit]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-audio-driver.git
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    tzapu/WiFiManager
    bblanchon/ArduinoJson@^6.21.3
build_flags =
    -DCORE_DEBUG_LEVEL=3
